name: "Deploy Website"
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@master
      - name: Install Composer Dependencies
        run: composer install --no-dev
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run production
      - name: Copy .env
        run: cp .env.hosting .env
      - name: Add .env variables
        run: |
          echo APP_ENV=production >> .env
          echo APP_DEBUG=false >> .env
          echo APP_URL=https://illini-metagamers.com >> .env
          echo STATAMIC_LICENSE_KEY=${{ secrets.STATAMIC_LICENSE_KEY }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
          echo MAIL_FROM_ADDRESS=${{ secrets.MAIL_USERNAME }} >> .env
      - name: Generate key
        run: php artisan key:generate
      - name: Cache clear & stache clear
        run: php artisan cache:clear && php please stache:clear && php please cache:clear && php artisan config:cache
      - name: Process images
        run: php please assets:generate-presets
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: "/public_html/"
