name: "Trigger Deploy Website"
on:
  push:
    branches:
      - main

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest
    
    steps:
      # Trigger Ploi deploy webhook
      - name: Deploy
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          webhook_url: ${{ secrets.PLOI_DEPLOY_WEBHOOK_URL }}