name: "Deploy Website"
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@master
      - name: Install Composer Dependencies
        run: composer install --no-dev
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run production
      - name: Copy .env
        run: cp .env.hosting .env
      - name: Add .env variables
        run: |
          echo APP_ENV=production >> .env
          echo APP_DEBUG=false >> .env
          echo APP_URL=https://illini-metagamers.com >> .env
          echo STATAMIC_LICENSE_KEY=${{ secrets.STATAMIC_LICENSE_KEY }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
          echo MAIL_FROM_ADDRESS=${{ secrets.MAIL_USERNAME }} >> .env
      - name: Generate key
        run: php artisan key:generate
      - name: Cache clear & stache clear
        run: php artisan cache:clear && php please stache:clear && php please cache:clear
      - name: Process images
        run: php please assets:generate-presets
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.FTP_HOST }}
          port: 22
          user: ${{ secrets.FTP_USER }}
          pass: ${{ secrets.FTP_PASSWORD }}
          parallel: 20
          # lftp settings
          onlyNewer: false
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: '/public_html/'
          reverse: true
          options: '--verbose --ignore-time --dereference --scan-all-first'
          ignoreFile: ".lftp_ignore"
